### ISSUE TITLE
"META" (experimental sequence) generation & upload notebook

### ISSUE THREAD

**Issue by felixbinder** [cogtoolslab/cognitive-ai-benchmarking#3]
- [ ] documentation on randomization in javascript vs ahead- [ ]of- [ ]time (with ahead- [ ]of- [ ]time the preferred method)
- [ ] create clean, annotated META notebook
- [ ] upload helper functions for mongoDB (these should just be easily importable from .py, give good warnings about potentially overwriting/dropping data in the stimuli database)
